### ISSUE TITLE
fixing deployment issues

### ISSUE THREAD

**Issue by prabincankod** [alby-francis/Vendor-api#1]
django project deployement issue on vercel.
Error:
WARN! Due to builds existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings

17:06:07.186 | Error: Unable to find any supported Python versions. 17:06:07.187 | Learn More: http://vercel.link/python-version
using python version  3.9.11 for the project and vercel also supports python version 3.9

**Comment by prabincankod** [comment]
@alby-francis i might help you resolve the deployment issues.

**Comment by alby-francis** [comment]
Thanks for coming through, Please let me know if you need any more information

**Comment by alby-francis** [comment]
Thanks @prabincankod for the help and finding the issue with the node version issue in vercel. Downgrading the vercel node version to 18.x resolved the deployment issue.
